# Funding / Sponsor links
# These links appear on the "Sponsor" button across all repos
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: qws941
