name: Bug Report
description: Report a bug or unexpected behavior
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug.
        Please fill out the sections below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low — Cosmetic or minor inconvenience
        - Medium — Broken feature with workaround available
        - High — Broken feature with no workaround
        - Critical — Data loss, security issue, or system outage
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Relevant environment details.
      placeholder: |
        - OS: e.g. Ubuntu 22.04, macOS 14
        - Runtime: e.g. Node.js 20.x, Python 3.12
        - Tool version: e.g. Terraform 1.9, Docker 27
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or log output.
    validations:
      required: false
