name: Feature Request
description: Suggest a new feature or improvement
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please describe your idea clearly so we can evaluate and prioritize it.

  - type: dropdown
    id: kind
    attributes:
      label: Kind
      description: What kind of change is this?
      options:
        - New feature — Something that doesn't exist yet
        - Enhancement — Improvement to existing functionality
        - Performance — Speed, efficiency, or resource optimization
        - Developer experience — Tooling, CI/CD, or workflow improvement
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution or approach.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false
